<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-201912201152" name="Test" tests="3" failures="1" timestamp="16 Mar 2020 11:06:30 GMT" time="10.11" errors="0">
  <testcase name="test03" time="0.005" classname="com.czq.Imooc.runcase.LoginCase"/>
  <testcase name="test04" time="0.001" classname="com.czq.Imooc.runcase.LoginCase"/>
  <testcase name="test05" time="0.017" classname="com.czq.Imooc.runcase.LoginCase">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at com.czq.Imooc.runcase.LoginCase.test05(LoginCase.java:78)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test05 -->
</testsuite> <!-- Test -->
