<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="10110" started-at="2020-03-16T11:06:20Z" finished-at="2020-03-16T11:06:30Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="10110" started-at="2020-03-16T11:06:20Z" finished-at="2020-03-16T11:06:30Z">
      <class name="com.czq.Imooc.runcase.LoginCase">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.czq.Imooc.runcase.LoginCase@55f3ddb1]" name="beforeClass" is-config="true" duration-ms="37" started-at="2020-03-16T19:06:20Z" finished-at="2020-03-16T19:06:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="beforeClass(java.lang.String, java.lang.String)[pri:0, instance:com.czq.Imooc.runcase.LoginCase@55f3ddb1]" name="beforeClass" is-config="true" duration-ms="9357" started-at="2020-03-16T19:06:20Z" finished-at="2020-03-16T19:06:29Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[http://www.imooc.com/]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="test03()[pri:0, instance:com.czq.Imooc.runcase.LoginCase@55f3ddb1]" name="test03" duration-ms="5" started-at="2020-03-16T19:06:29Z" finished-at="2020-03-16T19:06:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test03 -->
        <test-method status="PASS" signature="test04()[pri:0, instance:com.czq.Imooc.runcase.LoginCase@55f3ddb1]" name="test04" duration-ms="1" started-at="2020-03-16T19:06:29Z" finished-at="2020-03-16T19:06:29Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test04 -->
        <test-method status="FAIL" signature="test05()[pri:0, instance:com.czq.Imooc.runcase.LoginCase@55f3ddb1]" name="test05" duration-ms="17" started-at="2020-03-16T19:06:29Z" finished-at="2020-03-16T19:06:29Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [2] but found [1]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at org.testng.Assert.assertEquals(Assert.java:399)
	at com.czq.Imooc.runcase.LoginCase.test05(LoginCase.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test05 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.czq.Imooc.runcase.LoginCase@55f3ddb1]" name="afterClass" is-config="true" duration-ms="0" started-at="2020-03-16T19:06:30Z" finished-at="2020-03-16T19:06:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- com.czq.Imooc.runcase.LoginCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
